if hash code 2>/dev/null; then
  export EDITOR="code"
else
  export EDITOR="vim"
fi

if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi
if hash mise 2>/dev/null; then
  eval "$(mise activate bash)"
fi
if hash scmpuff 2>/dev/null; then
  eval "$(scmpuff init -s)"
fi
if hash fzf 2>/dev/null; then
  eval "$(fzf --bash)"
fi

# Source configuration files if they exist
for file in \
  "$HOME/.git-completion.bash" \
  "$HOME/.aliases" \
  "$HOME/.git-prompt.sh" \
  "$HOME/.bash_prompt" \
  "$HOME/.asdf/asdf.sh" \
  "$HOME/.asdf/completions/asdf.bash"; do

  [ -f "$file" ] && source "$file"
done
unset file

# Make git completion work when `git` is aliased to `g`
# http://askubuntu.com/a/62098/63773
complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null || complete -o default -o nospace -F _git g

export GPG_TTY=`tty`

# https://github.com/memkind/memkind/issues/33#issuecomment-648317086
if [[ "$(uname)" == 'Darwin' ]]; then
  alias nproc="sysctl -n hw.logicalcpu"
fi

# https://twitter.com/rockatanescu/status/1609518828882628609
RUBY_YJIT_ENABLE=1

# Don't add duplicate lines in the history.
HISTCONTROL=ignoredups

# Keep more history in memory and file.
HISTSIZE=10000
HISTFILESIZE=$HISTSIZE

# Append to the history file, don't overwrite it.
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Make "**" in a pathname expansion context match all files
# and zero or more directories and subdirectories.
shopt -s globstar
