source "$HOME/.shell-helpers.sh"

select_editor
add_common_dirs_to_path

source_if_exists "$HOME/.aliases"
source_if_exists "$HOME/.asdf/asdf.sh"
source_if_exists "$HOME/.git-prompt.sh"

if type brew > /dev/null; then
  brew_cmd="brew"
elif [ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  brew_cmd="/home/linuxbrew/.linuxbrew/bin/brew"
fi

if [ -n "$brew_cmd" ]; then
  eval "$($brew_cmd shellenv)"
fi
if type rbenv > /dev/null; then
  eval "$(rbenv init - zsh)"
fi
if type mise > /dev/null; then
  eval "$(mise activate zsh)"
fi
if type scmpuff > /dev/null; then
  eval "$(scmpuff init -s)"
fi
if type fzf > /dev/null; then
  source <(fzf --zsh)
fi
if type openclaw > /dev/null; then
  source <(openclaw completion --shell zsh)
fi

zstyle ':completion:*' special-dirs true

zstyle ':completion:*:*:git:*' script ~/.git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

# Keep more history in memory and file.
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=$HISTSIZE

# Share history across all sessions immediately.
setopt SHARE_HISTORY

# Add timestamps to history entries.
setopt EXTENDED_HISTORY

# Allow bare directory names to change directories automatically.
setopt autocd

# Don't store duplicate entries in the history.
setopt HIST_IGNORE_DUPS

setopt interactivecomments

setopt PROMPT_SUBST
NEWLINE=$'\n'
if [[ "${(L)$(hostname -s)}" == *macbook* ]]; then
  HOSTCOLOR="green"
else
  HOSTCOLOR="magenta"
fi
PROMPT='${NEWLINE}%F{248}%* %F{$HOSTCOLOR}%n@%m %F{yellow}%~%F{cyan}$(__git_ps1)%f${NEWLINE}❯ '

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export GPG_TTY=`tty`

# https://github.com/memkind/memkind/issues/33#issuecomment-648317086
if [[ "$(uname)" == 'Darwin' ]]; then
  alias nproc="sysctl -n hw.logicalcpu"
fi

# https://unix.stackexchange.com/questions/48577/modifying-the-zsh-shell-word-split
WORDCHARS=${WORDCHARS//[\.\/\-_]}

# https://twitter.com/rockatanescu/status/1609518828882628609
RUBY_YJIT_ENABLE=1

# nvm installed via Homebrew
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# Must be called after compinit
if type zoxide > /dev/null; then
  eval "$(zoxide init zsh)"
fi

[ -f "$HOME/.secret-env-vars" ] && source "$HOME/.secret-env-vars"
